services:
  postgres:
    image: postgres:latest
    container_name: todo_postgres
    environment:
      - POSTGRES_DB=todoDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge